config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :models
  resources :mitarbeiters

  root to: 'pages#home'

end

app/models/mitarbeiter.rb
class Mitarbeiter < ActiveRecord::Base
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mitarbeiters_controller.rb
class MitarbeitersController < ApplicationController
  before_action :set_mitarbeiter, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /mitarbeiters
  # GET /mitarbeiters.json
  def index
    @mitarbeiters = Mitarbeiter.all
  end

  # GET /mitarbeiters/1
  # GET /mitarbeiters/1.json
  def show
  end

  # GET /mitarbeiters/new
  def new
    @mitarbeiter = Mitarbeiter.new
  end

  # GET /mitarbeiters/1/edit
  def edit
  end

  # POST /mitarbeiters
  # POST /mitarbeiters.json
  def create
    @mitarbeiter = Mitarbeiter.new(mitarbeiter_params)

    respond_to do |format|
      if @mitarbeiter.save
        format.html { redirect_to @mitarbeiter, notice: 'Mitarbeiter was successfully created.' }
        format.json { render :show, status: :created, location: @mitarbeiter }
      else
        format.html { render :new }
        format.json { render json: @mitarbeiter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mitarbeiters/1
  # PATCH/PUT /mitarbeiters/1.json
  def update
    respond_to do |format|
      if @mitarbeiter.update(mitarbeiter_params)
        format.html { redirect_to @mitarbeiter, notice: 'Mitarbeiter was successfully updated.' }
        format.json { render :show, status: :ok, location: @mitarbeiter }
      else
        format.html { render :edit }
        format.json { render json: @mitarbeiter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mitarbeiters/1
  # DELETE /mitarbeiters/1.json
  def destroy
    @mitarbeiter.destroy
    respond_to do |format|
      format.html { redirect_to mitarbeiters_url, notice: 'Mitarbeiter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mitarbeiter
      @mitarbeiter = Mitarbeiter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mitarbeiter_params
      params.require(:mitarbeiter).permit(:pesonalnummer, :vorname, :nachname, :handy, :festnetz, :az_monat, :az_konto)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mitarbeiters_helper.rb
module MitarbeitersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
  <link href="/assets/style.css" media="screen" rel="stylesheet" >
</head>
	<body>

	<%= render '/pages/header' %>

	<%= yield %>

	<%= render '/pages/footer' %>

	</body>
</html>

app/views/mitarbeiters/_form.html.erb
<%= form_for(@mitarbeiter, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @mitarbeiter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mitarbeiter.errors.count, "error") %> prohibited this mitarbeiter from being saved:</h2>

      <ul>
      <% @mitarbeiter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<fieldset>

  <div class="field group-control">
    <%= f.label :pesonalnummer, class: "control-label" %><br>
    <div class="controls">
    <%= f.number_field :pesonalnummer %>
    </div>
  </div>
  <div class="field">
    <%= f.label :vorname %><br>
    <%= f.text_field :vorname %>
  </div>
  <div class="field">
    <%= f.label :nachname %><br>
    <%= f.text_field :nachname %>
  </div>
  <div class="field">
    <%= f.label :handy %><br>
    <%= f.text_field :handy %>
  </div>
  <div class="field">
    <%= f.label :festnetz %><br>
    <%= f.text_field :festnetz %>
  </div>
  <div class="field">
    <%= f.label :az_monat %><br>
    <%= f.text_field :az_monat %>
  </div>
  <div class="field">
    <%= f.label :az_konto %><br>
    <%= f.text_field :az_konto %>
  </div>
  <div class="form-actions">
    <%= f.submit %>
  </div>
</fieldset>
<% end %>

app/views/mitarbeiters/edit.html.erb
<h1>Editing Mitarbeiter</h1>

<%= render 'form' %>

<%= link_to 'Show', @mitarbeiter %> |
<%= link_to 'Back', mitarbeiters_path %>

app/views/mitarbeiters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mitarbeiter</h1>

<table class="table table-bordered">
  <thead style="color: white; background-color: #531">
    <tr>
      <th>Pesonalnummer</th>
      <th>Vorname</th>
      <th>Nachname</th>
      <th>Handy</th>
      <th>Festnetz</th>
      <th>Az monat</th>
      <th>Az konto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mitarbeiters.each do |mitarbeiter| %>
      <tr>
        <td><%= mitarbeiter.pesonalnummer %></td>
        <td><%= mitarbeiter.vorname %></td>
        <td><%= mitarbeiter.nachname %></td>
        <td><%= mitarbeiter.handy %></td>
        <td><%= mitarbeiter.festnetz %></td>
        <td><%= mitarbeiter.az_monat %></td>
        <td><%= mitarbeiter.az_konto %></td>
        <td><%= link_to 'Show', mitarbeiter %></td>
        <td><%= link_to 'Edit', edit_mitarbeiter_path(mitarbeiter) %></td>
        <td><%= link_to 'Destroy', mitarbeiter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to('Neu Mitarbeiter', new_mitarbeiter_path, class: "btn btn-warning")%>

app/views/mitarbeiters/new.html.erb
<h1>New Mitarbeiter</h1>

<%= render 'form' %>

<%= link_to 'Back', mitarbeiters_path %>

app/views/mitarbeiters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pesonalnummer:</strong>
  <%= @mitarbeiter.pesonalnummer %>
</p>

<p>
  <strong>Vorname:</strong>
  <%= @mitarbeiter.vorname %>
</p>

<p>
  <strong>Nachname:</strong>
  <%= @mitarbeiter.nachname %>
</p>

<p>
  <strong>Handy:</strong>
  <%= @mitarbeiter.handy %>
</p>

<p>
  <strong>Festnetz:</strong>
  <%= @mitarbeiter.festnetz %>
</p>

<p>
  <strong>Az monat:</strong>
  <%= @mitarbeiter.az_monat %>
</p>

<p>
  <strong>Az konto:</strong>
  <%= @mitarbeiter.az_konto %>
</p>

<%= link_to 'Edit', edit_mitarbeiter_path(@mitarbeiter) %> |
<%= link_to 'Back', mitarbeiters_path %>

app/views/pages/_footer.html.erb
<div class="wrapper">
    <div class="push"></div>
</div>
<div class="footer">
    <p>&copy; Trecker.com 2015</p>
</div>

app/views/pages/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Trecker.com</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Planung <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Kunden <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Lager <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Auswertungen <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Verwaltung <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          	<li><%= link_to 'Mitarbeiters', mitarbeiters_path %></li>
            <li><a href="#">Maschinen</a></li>
            <li><a href="#">Kunden</a></li>
            <li><a href="#">Lieferanten</a></li>
            <li><a href="#">Subunternehmer</a></li>

	        <li class="divider"></li>
            
            <li><a href="#">Gespanne</a></li>
            <li><a href="#">Mschinengruppen</a></li>
	        
	        <li class="divider"></li>
            
            <li><a href="#">Betriebs-Einstellungen</a></li>
            <li><a href="#">Benutzer-Einstellungen</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Hilfe <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>


      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <% if user_signed_in? %>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">You are logged in as <%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to('Edit user', edit_user_registration_path) %></li>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
          </ul>
          <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Sign In", new_user_session_path %></li>
        </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/pages/home.html.erb
<% @current_diesel_price = 2.14 %>

<h1>Diese Woche:</h1>

<div>
	<h2>Dieselpreis</h2>
	<div>
		<h4>Aktuell Dieselpreis: <%= @current_diesel_price %>€</h4>
		<a target="_blank" href="http://www.shell.de/products-services/on-the-road/fuels/fuel-pricing/current-prices.html">Preisentwicklung</a>
	</div>
</div>